import {
  CoatManifestFile,
  CoatManifestFileType,
} from "../types/coat-manifest-file";

/**
 * Creates files that are generated by default if the template
 * does not overwrite them.
 *
 * For now it only contains a .gitignore file to prevent
 * empty templates that check in their node_modules
 * by default.
 */
export function getDefaultFiles(): CoatManifestFile[] {
  return [
    {
      file: ".gitignore",
      content: `node_modules

# coat local files
/.coat
`,
      type: CoatManifestFileType.Text,
      once: true,
    },
  ];
}
