import difference from "lodash/difference";
import { CoatContext } from "../types/coat-context";
import { CoatLockfile } from "../types/coat-lockfile";
import { getNormalizedFilePath } from "../util/get-normalized-file-path";

export function getUnmanagedFiles(
  newLockfile: CoatLockfile,
  context: CoatContext
): string[] {
  if (!context.coatLockfile) {
    return [];
  }

  // Get all files that are in the old lockfile
  // but no longer in the new lockfile. This means they
  // have been added previously by coat, but are no longer
  // generated by this project.
  const unmanagedFiles = difference(
    context.coatLockfile.files.map((file) => file.path),
    newLockfile.files.map((file) => file.path)
  );

  // Normalize and retrieve the absolute file paths of
  // the unmanaged files to be able to delete them without
  // relying on the process's current working directory
  return unmanagedFiles.map((filePath) =>
    getNormalizedFilePath(filePath, context)
  );
}
